### PR TITLE
Use crypto/rand instead of math/rand and formatting changes

### PR DESCRIPTION
**Pull request by eNV25**
### 1. What does this change do, exactly?

Replaces uses of math/rand with crypto/rand.

Formats code with gofmt, etc.

~~Update quic-go indirect dep to build with `go1.18`. So it includes #2.~~ Not needed anymore.

Update direct deps.

### 2. Please link to the relevant issues.

None

### 3. Which documentation changes (if any) need to be made because of this PR?

None

### 4. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I made pull request as minimal and simple as possible. If change is not small or additional dependencies are required, I opened an issue to propose and discuss the design first
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code

### CODE REVIEW

**Comment by eNV25** [comment]
Must update `randUint64N` to handle `nil`.

**Comment by klzgrad** [comment]
No clear reason why crypto/rand is required. Go fmt is fixed separately.

**Comment by eNV25** [comment]
https://pkg.go.dev/math/rand
```
Package rand implements pseudo-random number generators unsuitable for security-sensitive work.

Random numbers are generated by a Source. Top-level functions, such as Float64 and Int, use a default shared Source that produces a deterministic sequence of values each time a program is run. Use the Seed function to initialize the default Source if different behavior is required for each run. The default Source is safe for concurrent use by multiple goroutines, but Sources created by NewSource are not.

This package's outputs might be easily predictable regardless of how it's seeded. For random numbers suitable for security-sensitive work, see the crypto/rand package. 
```

Also, `math/rand.Seed` is not called.

**Comment by klzgrad** [comment]
https://github.com/klzgrad/forwardproxy/commit/520725d47be6f335be535335328aa4da07dc360b

Not needed to be cryptographically secure. Does not care about double seeding.

**Comment by showgood163** [comment]
https://github.com/v2fly/v2ray-core/issues/2054

Is this issue related to this pull requests?

**Comment by eNV25** [comment]
Yes probably.

There are two issues here.
- `math/rand` is used instead of `crypto/rand`. `math/rand` is a pseudo-random number generator. Generated pseudo-random could be predicted with enough information.

- `math/rand` is used incorrectly. Since the generator is not seeded, it will produce the same sequence of pseudo-random every execution.

**Comment by klzgrad** [comment]
10^9 seeds and pseudo random numbers should be more than enough against traffic classification. The attack being proposed is that for each website fingerprint the attacker could enumerate all the seeds and synthesize 10^9 training samples. In terms of ML training systems, it's more of a resource waste than worthwhile attack.

Seeding is added in the commit in disregard of possible double seeding.

**Comment by klzgrad** [comment]
VMess seems to emit paddings in clear text. Nonsuch issue here.

**Pull request closed without merging**
