### PR TITLE
fix: fix caddy v2.7.x runtime error: ResponseWriter doesn't implement…

### PR DESCRIPTION
**Pull request by ghost**
… http.Flusher

### 1. What does this change do, exactly?
fix caddy v2.7.x runtime error: ResponseWriter doesn't implement http.Flusher by using ResponseController introduced in golang v1.20

### 2. Please link to the relevant issues.
https://github.com/klzgrad/naiveproxy/issues/575
https://github.com/caddyserver/forwardproxy/issues/107

### 3. Which documentation changes (if any) need to be made because of this PR?
None

### 4. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I made pull request as minimal and simple as possible. If change is not small or additional dependencies are required, I opened an issue to propose and discuss the design first
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code

### 5. PS
This PR does not fix an issue that caused the forwardproxy to not work when turning on the LOG directive in Caddyfile https://github.com/klzgrad/naiveproxy/issues/550#issuecomment-1683945230

### CODE REVIEW

**Comment by klzgrad** [comment]
@Chilledheart Can you test if this works?

**Comment by Chilledheart** [comment]
> @Chilledheart Can you test if this works?

No, it is not working. 
I tested github.com, google.com and etc in some vm at seatle.

Below configuration is added.
```
  log {
    output file /var/log/caddy.log {
      roll_disabled
    }
    format console
    level  INFO
  }
```

**Comment by ghost** [comment]
"5. PS This PR does not" this PR is not for fix that log issue

**Comment by Chilledheart** [comment]
Okay, then. I tested it without log option. It seems working now (both of google.com and github.com,  with naiveproxy in linux and shadowrocket in ios)

**Comment by Chilledheart** [comment]
Built with `go version go1.21.3 linux/amd64`

**Pull request merged**
